# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок актуальной статьи 1')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='actual', verbose_name='Изображение актуальной статьи 1')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='Текст актуальной статьи 1')),
                ('header_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок актуальной статьи 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='actual', verbose_name='Изображение актуальной статьи 1')),
                ('text_2', models.TextField(blank=True, null=True, verbose_name='Текст актуальной статьи 1')),
                ('header_3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок актуальной статьи 1')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='actual', verbose_name='Изображение актуальной статьи 1')),
                ('text_3', models.TextField(blank=True, null=True, verbose_name='Текст актуальной статьи 1')),
            ],
            options={
                'verbose_name': 'Настройки актуальных статей',
                'verbose_name_plural': 'Настройки актуальных статей',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priem', models.TextField(blank=True, help_text='Блок Открыт прием статей', null=True, verbose_name='Прием статей')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='Главная картинка')),
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
            },
        ),
    ]
