# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualarticles',
            name='number_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер статиьи 1'),
        ),
        migrations.AddField(
            model_name='actualarticles',
            name='number_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер статиьи 2'),
        ),
        migrations.AddField(
            model_name='actualarticles',
            name='number_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер статиьи 3'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='header_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок актуальной статьи 2'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='header_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок актуальной статьи 3'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='actual', verbose_name='Изображение актуальной статьи 2'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='actual', verbose_name='Изображение актуальной статьи 3'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Текст актуальной статьи 2'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='text_3',
            field=models.TextField(blank=True, null=True, verbose_name='Текст актуальной статьи 3'),
        ),
    ]
