# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_auto_20170501_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('examle_link', models.URLField(verbose_name='Ссылка на пример оформления')),
                ('information_link', models.URLField(verbose_name='Ссылка на сопроводительную информацию')),
            ],
            options={
                'verbose_name': 'Настройки страницы требований',
                'verbose_name_plural': 'Настройки страницы требований',
            },
        ),
    ]
