# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_reqpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.TextField(verbose_name='Текст - Оплата публикаций')),
                ('editor', models.TextField(verbose_name='Текст - Оплата оформления статьи')),
                ('yandex_widget_1', models.TextField(verbose_name='Виджет - Оплата публикаций')),
                ('yandex_widget_2', models.TextField(verbose_name='Виджет - Оплата оформления статьи')),
            ],
            options={
                'verbose_name': 'Настройки страницы оплаты',
                'verbose_name_plural': 'Настройки страницы оплаты',
            },
        ),
    ]
