# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_paymentpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Настройки страницы информации о спецвыпуске',
                'verbose_name_plural': 'Настройки страницы информации о спецвыпуске',
            },
        ),
    ]
