# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0006_specialpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualarticles',
            name='header_1',
            field=models.CharField(max_length=150, verbose_name='Заголовок актуальной статьи 1'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='header_2',
            field=models.CharField(max_length=150, verbose_name='Заголовок актуальной статьи 2'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='header_3',
            field=models.CharField(max_length=150, verbose_name='Заголовок актуальной статьи 3'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='image_1',
            field=models.ImageField(upload_to='actual', verbose_name='Изображение актуальной статьи 1'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='image_2',
            field=models.ImageField(upload_to='actual', verbose_name='Изображение актуальной статьи 2'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='image_3',
            field=models.ImageField(upload_to='actual', verbose_name='Изображение актуальной статьи 3'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='link_1',
            field=models.CharField(max_length=150, verbose_name='Ссылка статиьи 1'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='link_2',
            field=models.CharField(max_length=150, verbose_name='Ссылка статиьи 2'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='link_3',
            field=models.CharField(max_length=150, verbose_name='Ссылка статиьи 3'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='text_1',
            field=models.TextField(verbose_name='Текст актуальной статьи 1'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='text_2',
            field=models.TextField(verbose_name='Текст актуальной статьи 2'),
        ),
        migrations.AlterField(
            model_name='actualarticles',
            name='text_3',
            field=models.TextField(verbose_name='Текст актуальной статьи 3'),
        ),
    ]
