# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0007_auto_20170501_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='email',
            field=models.EmailField(default='synergy-journal-question@mail.ru', max_length=254, verbose_name='Почта для вопросов'),
        ),
    ]
