# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0008_mainpage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='bottom',
            field=models.TextField(default='', verbose_name='Футер'),
            preserve_default=False,
        ),
    ]
