# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0010_auto_20170911_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpage',
            name='yandex_widget_1',
            field=models.TextField(default='', verbose_name='Виджет - Оплата публикаций'),
            preserve_default=False,
        ),
    ]
