# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название статьи (Rus)')),
                ('title_eng', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название статьи (Eng)')),
                ('authors', models.CharField(blank=True, max_length=150, null=True, verbose_name='Авторы')),
                ('grade', models.CharField(blank=True, max_length=150, null=True, verbose_name='Степень')),
                ('workplace', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место работы/учебы')),
                ('annotation_rus', models.TextField(blank=True, null=True, verbose_name='Аннотация (Rus)')),
                ('annotation_end', models.TextField(blank=True, null=True, verbose_name='Аннотация (Eng)')),
                ('keywords_rus', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ключевые слова (Rus)')),
                ('keywords_end', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ключевые слова (Eng)')),
                ('url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Порядковый номер журнала')),
                ('image', models.ImageField(blank=True, null=True, upload_to='magazine', verbose_name='Обложка')),
                ('special', models.BooleanField(default=False, verbose_name='Специальный выпуск')),
            ],
            options={
                'verbose_name': 'Вид науки',
                'verbose_name_plural': 'Виды наук',
            },
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Вид науки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='science', verbose_name='Изображение')),
                ('ordering', models.IntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Вид науки',
                'verbose_name_plural': 'Виды наук',
            },
        ),
    ]
