# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20170411_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Порядковый номер журнала'),
        ),
        migrations.AlterField(
            model_name='science',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Вид науки'),
        ),
    ]
