# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20170411_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='science',
            options={'verbose_name': 'Вид наук', 'verbose_name_plural': 'Виды наук'},
        ),
        migrations.AddField(
            model_name='article',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Magazine', verbose_name='Выпуск журнала'),
        ),
        migrations.AddField(
            model_name='article',
            name='science',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Science', verbose_name='Вид наук'),
        ),
    ]
