# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_article_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='grade',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Степень'),
        ),
        migrations.AlterField(
            model_name='article',
            name='input_data',
            field=models.TextField(blank=True, null=True, verbose_name='Выходные данные'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords_end',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ключевые слова (Eng)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords_rus',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ключевые слова (Rus)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название статьи (Rus)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_eng',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название статьи (Eng)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='workplace',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Место работы/учебы'),
        ),
    ]
