# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20170418_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='magazine_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок в журнале'),
        ),
        migrations.AddField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Страницы в журнале'),
        ),
    ]
