# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20170420_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='input_data',
        ),
    ]
