# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_article_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='magazine_authors',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Авторы в журнале'),
        ),
    ]
