# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20170424_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='science',
            options={'ordering': ['ordering'], 'verbose_name': 'Вид наук', 'verbose_name_plural': 'Виды наук'},
        ),
        migrations.AddField(
            model_name='magazine',
            name='url',
            field=models.CharField(blank=True, help_text='Ссылка на Google Drive', max_length=300, null=True, verbose_name='Полный выпуск'),
        ),
    ]
