# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialMagazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=300, unique=True, verbose_name='Номер журнала')),
                ('day', models.IntegerField(verbose_name='День')),
                ('mouth', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('image', models.ImageField(blank=True, null=True, upload_to='magazine', verbose_name='Обложка')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Номер журнала')),
                ('organizator', models.TextField(blank=True, null=True, verbose_name='Номер журнала')),
                ('example', models.TextField(blank=True, null=True, verbose_name='Пример выходных данных')),
                ('url', models.CharField(blank=True, help_text='Ссылка на Google Drive', max_length=300, null=True, verbose_name='Полный выпуск')),
            ],
            options={
                'verbose_name_plural': 'Специльные выпуски журнала',
                'verbose_name': 'Специльный выпуск журнала',
                'ordering': ('year', 'mouth'),
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='special',
        ),
    ]
