# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20170427_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='badge',
            field=models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='Бейджик для соцсетей'),
        ),
    ]
