# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20180407_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='image',
            field=models.ImageField(upload_to='magazine', verbose_name='Обложка'),
        ),
    ]
